added sonarube quality gate

diff --git a/.github/workflows/sonarqube.yaml b/.github/workflows/sonarqube.yaml
--- a/.github/workflows/sonarqube.yaml
+++ b/.github/workflows/sonarqube.yaml
@@ -57,19 +57,19 @@ jobs:
         SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
 
     # Quality Gate Check
-#    - name: SonarQube Quality Gate check
-#      id: sonarqube-quality-gate-check
-#      uses: sonarsource/sonarqube-quality-gate-action@master
-#      timeout-minutes: 5
-#      env:
-#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-#        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-#
-#    # Optional: Fail the job if Quality Gate fails
-#    - name: "Quality Gate Status"
-#      run: |
-#        echo "Quality Gate Status: ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
-#        if [ "${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}" != "PASSED" ]; then
-#          echo "Quality Gate failed!"
-#          exit 1
-#        fi
+    - name: SonarQube Quality Gate check
+      id: sonarqube-quality-gate-check
+      uses: sonarsource/sonarqube-quality-gate-action@master
+      timeout-minutes: 5
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+
+    # Optional: Fail the job if Quality Gate fails
+    - name: "Quality Gate Status"
+      run: |
+        echo "Quality Gate Status: ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
+        if [ "${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}" != "PASSED" ]; then
+          echo "Quality Gate failed!"
+          exit 1
+        fi
